###

## Создание предолжения
POST http://localhost:4000/offers HTTP/1.1

###

## Список предложений

GET http://localhost:4000/offers HTTP/1.1

###

## Детальная информация о конкретном предолжении (show по offerId)
GET http://localhost:4000/offers/1323 HTTP/1.1

###

## Удаление информации о конкретном предолжении (delete по offerId)
DELETE http://localhost:4000/offers/delete/1323 HTTP/1.1

###

## Обновление информации о конкретном предолжении (update по offerId)
PATCH http://localhost:4000/offers/update/1323 HTTP/1.1

###


## Получение списка премиальных предложений для города
GET http://localhost:4000/offers/premium/Berlin HTTP/1.1

###

## Получение списка избранных предложений для пользователя (по userID)
GET http://localhost:4000/offers/favorites/213 HTTP/1.1

###

## Получение списка комментариев для предложения (по offerId)
GET http://localhost:4000/offers/6212/comments HTTP/1.1

###

## Список комментариев к объявлению
GET http://localhost:4000/offers/628a27d729c45f2bf9f6806a/comments HTTP/1.1

###

